# Generated by Django 5.1.15 on 2026-06-18 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_eventlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('url', models.URLField(blank=True, verbose_name='link da loja')),
                ('status', models.CharField(choices=[('available', 'Disponível'), ('reserved', 'Reservado')], default='available', max_length=10)),
                ('claimed_by_name', models.CharField(blank=True, max_length=120, verbose_name='reservado por')),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='events.event')),
            ],
            options={
                'verbose_name': 'presente',
                'verbose_name_plural': 'presentes',
                'ordering': ['created_at'],
            },
        ),
    ]
