# Generated by Django 5.1.15 on 2026-06-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='companion_names',
            field=models.JSONField(blank=True, default=list, verbose_name='nomes dos acompanhantes'),
        ),
    ]
