# Generated by Django 5.1.15 on 2026-06-17 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
        ('rsvps', '0002_rsvp_companion_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='invitation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rsvp', to='invitations.invitation'),
        ),
    ]
