# Generated by Django 5.1.15 on 2026-06-17 18:15

import apps.events.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=140, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.events.models.event_photo_path, verbose_name='foto')),
                ('address', models.CharField(max_length=255, verbose_name='endereço')),
                ('location_link', models.URLField(blank=True, verbose_name='link da localização')),
                ('starts_at', models.DateTimeField(verbose_name='data e horário')),
                ('note', models.TextField(blank=True, verbose_name='observação')),
                ('allow_companions', models.BooleanField(default=False, verbose_name='permite acompanhantes')),
                ('max_companions', models.PositiveSmallIntegerField(default=0, verbose_name='máx. de acompanhantes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
            ],
            options={
                'verbose_name': 'evento',
                'verbose_name_plural': 'eventos',
                'ordering': ['-starts_at'],
            },
        ),
    ]
