# Generated by Django 5.1.15 on 2026-06-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpurchase',
            name='kind',
            field=models.CharField(choices=[('capacity', 'Faixa de capacidade'), ('gift', 'Lista de presentes')], default='capacity', max_length=10),
        ),
        migrations.AlterField(
            model_name='eventpurchase',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='capacidade'),
        ),
    ]
