# Generated by Django 5.1.15 on 2026-07-03 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_eventpurchase_kind_alter_eventpurchase_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(blank=True, max_length=60, verbose_name='nome comercial'),
        ),
    ]
